// <auto-generated />
using DinkesAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DinkesAPI.Migrations
{
    [DbContext(typeof(DinkesContext))]
    [Migration("20251023105629_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DinkesAPI.Models.Faskes", b =>
                {
                    b.Property<int>("ID_faskes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_faskes"));

                    b.Property<string>("alamat_faskes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("jenis_faskes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nama_faskes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_faskes");

                    b.ToTable("Faskes");

                    b.HasData(
                        new
                        {
                            ID_faskes = 1,
                            alamat_faskes = "Jl. Soekarno-Hatta No.123",
                            jenis_faskes = "Puskesmas",
                            nama_faskes = "Puskesmas Bandung Kidul"
                        },
                        new
                        {
                            ID_faskes = 2,
                            alamat_faskes = "Jl. Kopo No.45",
                            jenis_faskes = "Rumah Sakit",
                            nama_faskes = "RSUD Kota Bandung"
                        });
                });

            modelBuilder.Entity("DinkesAPI.Models.JumlahTenagaMedis", b =>
                {
                    b.Property<int>("ID_Jumlahtm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Jumlahtm"));

                    b.Property<int>("ID_faskes")
                        .HasColumnType("int");

                    b.Property<int>("bidan")
                        .HasColumnType("int");

                    b.Property<int>("dokter")
                        .HasColumnType("int");

                    b.Property<int>("perawat")
                        .HasColumnType("int");

                    b.HasKey("ID_Jumlahtm");

                    b.HasIndex("ID_faskes");

                    b.ToTable("JumlahTenagaMedis");

                    b.HasData(
                        new
                        {
                            ID_Jumlahtm = 1,
                            ID_faskes = 1,
                            bidan = 3,
                            dokter = 5,
                            perawat = 12
                        },
                        new
                        {
                            ID_Jumlahtm = 2,
                            ID_faskes = 2,
                            bidan = 10,
                            dokter = 15,
                            perawat = 30
                        });
                });

            modelBuilder.Entity("DinkesAPI.Models.JumlahTenagaMedis", b =>
                {
                    b.HasOne("DinkesAPI.Models.Faskes", "Faskes")
                        .WithMany("JumlahTenagaMedis")
                        .HasForeignKey("ID_faskes")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faskes");
                });

            modelBuilder.Entity("DinkesAPI.Models.Faskes", b =>
                {
                    b.Navigation("JumlahTenagaMedis");
                });
#pragma warning restore 612, 618
        }
    }
}
