// <auto-generated />
using DinkesAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DinkesAPI.Migrations
{
    [DbContext(typeof(DinkesContext))]
    partial class DinkesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DinkesAPI.Models.Faskes", b =>
                {
                    b.Property<string>("ID_faskes")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("alamat_faskes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("jenis_faskes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nama_faskes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_faskes");

                    b.ToTable("Faskes");
                });

            modelBuilder.Entity("DinkesAPI.Models.JumlahTenagaMedis", b =>
                {
                    b.Property<string>("ID_Jumlahtm")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ID_faskes")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("bidan")
                        .HasColumnType("int");

                    b.Property<int>("dokter")
                        .HasColumnType("int");

                    b.Property<int>("perawat")
                        .HasColumnType("int");

                    b.HasKey("ID_Jumlahtm");

                    b.HasIndex("ID_faskes");

                    b.ToTable("JumlahTenagaMedis");
                });

            modelBuilder.Entity("DinkesAPI.Models.JumlahTenagaMedis", b =>
                {
                    b.HasOne("DinkesAPI.Models.Faskes", "Faskes")
                        .WithMany("JumlahTenagaMedis")
                        .HasForeignKey("ID_faskes")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faskes");
                });

            modelBuilder.Entity("DinkesAPI.Models.Faskes", b =>
                {
                    b.Navigation("JumlahTenagaMedis");
                });
#pragma warning restore 612, 618
        }
    }
}
